### PR TITLE
fix(codegen): alignment of struct fields

### LINKED ISSUE #274: The Mun compiler does not properly align struct fields
A comparison of LLVM IR generated by the Mun compiler:
image

with LLVM IR generated by `rustc`:
image

shows that our struct fields are not properly aligned.

To solve this, we should add padding before/after struct fields.

### PR DESCRIPTION
**Pull request by Wodann**
Fixes #274.

### CODE REVIEW

File: crates/mun_codegen/src/ir/types.rs [hunk 1]
```diff
@@ -1,4 +1,5 @@
 use crate::value::{AsValue, IrValueContext, SizedValueType, TransparentValue, Value};
+use itertools::Itertools;
```
Comment (baszalmstra) [inline crates/mun_codegen/src/ir/types.rs:2]: This doesn't seem to be used.

File: crates/mun_codegen_macros/src/lib.rs [hunk 2]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+                            ((data_size + align - 1) / align) * align
+                        }
+
+                        // Aliasing to make sure that all procedurally generated macros can use the
+                        // same variable name.
+                        let type_context = context.type_context;
+                        let field_padding = #field_padding_values;
+
+                        let struct_type = Self::get_ir_type(context.type_context);
+                        // eprintln!("Constructing: {:?}", struct_type.print_to_string().to_string());
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:168]: Can this be removed?

File: crates/mun_codegen_macros/src/lib.rs [hunk 3]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+                                    .map(|_| ty.const_int(0, false))
+                                    .collect();
+
+                                ty.const_array(&chunks).into()
+                            })
+                            .interleave(field_values.into_iter())
+                            .collect();
+
+                        let value = struct_type.const_named_struct(&struct_fields);
+                        // eprintln!("Done");
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:194]: Can this be removed?

File: crates/mun_codegen_macros/src/lib.rs [hunk 4]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+            });
+
+            // Generate a list of where clauses that ensure that we can cast each field to an
+            // `inkwell::values::BasicTypeValue`
+            let field_types_values = struct_data.fields.iter().enumerate().map(|(idx, f)| {
+                let name = f.ident.as_ref().map(|i| quote! { #i }).unwrap_or_else(|| quote! { #idx });
+                quote! {
+                    {
+                        let value = crate::value::AsValueInto::<'ink, inkwell::values::BasicValueEnum<'ink>>::as_value_into(&self. #name, context);
+                        // eprintln!("- {:?}", value.get_type());
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:92]: Can this be removed?

File: crates/mun_codegen_macros/src/lib.rs [hunk 5]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
-                struct_ty.set_body(&[
-                    #(#field_types),*
-                ], false);
-                struct_ty
-            }
-        }
+                }
+            });
+
+            // Generate Phase
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:98]: What does this comment mean exactly?

File: crates/mun_codegen_macros/src/lib.rs [hunk 6]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+            (quote! {
+                impl<'ink> crate::value::ConcreteValueType<'ink> for #ident {
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:100]: It would help me to add some comments here, e.g.:
```suggestion
                // A struct always has an inkwell StructValue as a result type
                impl<'ink> crate::value::ConcreteValueType<'ink> for #ident {
```

File: crates/mun_codegen_macros/src/lib.rs [hunk 7]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+                    type Value = inkwell::values::StructValue<'ink>;
+                }
+
+                impl<'ink> crate::value::SizedValueType<'ink> for #ident {
+                    fn get_ir_type(context: &crate::value::IrTypeContext<'ink, '_>) -> inkwell::types::StructType<'ink> {
+                        let key = std::any::type_name::<#ident>();
+                        match context.struct_types.borrow().get(&key) {
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:107]: Maybe add some comments here

File: crates/mun_codegen_macros/src/lib.rs [hunk 8]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+                            Some(value) => {
+                                return *value;
+                            }
+                            None => (),
+                        };
+
+                        let struct_ty = context.context.opaque_struct_type(key);
+                        context.struct_types.borrow_mut().insert(key, struct_ty);
+
+                        fn padded_size(align: usize, data_size: usize) -> usize {
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:117]: What does this do exactly?

File: crates/mun_codegen_macros/src/lib.rs [hunk 9]
```diff
@@ -27,175 +21,189 @@ pub fn as_value_derive(input: TokenStream) -> TokenStream {
...
+                        // Aliasing to make sure that all procedurally generated macros can use the
+                        // same variable name.
+                        let type_context = context;
+
+                        let field_types = vec![ #(#field_types),* ];
+                        let field_padding = #field_padding_types;
+                        let struct_fields: Vec<_> = field_padding
+                            .into_iter()
+                            .map(|p| {
+                                let (ty, num_chunks) = if p % 8 == 0 {
```
Comment (baszalmstra) [inline crates/mun_codegen_macros/src/lib.rs:130]: What does this do?

File: crates/mun_codegen/Cargo.toml [hunk 10]
```diff
@@ -15,6 +15,7 @@ categories = ["Game development", "Mun"]
 [dependencies]
 abi = { version = "=0.2.0", path = "../mun_abi", package = "mun_abi" }
 hir = { version = "=0.2.0", path = "../mun_hir", package = "mun_hir" }
+itertools = "0.9.0"
```
Comment (baszalmstra) [inline crates/mun_codegen/Cargo.toml:18]: Is this actually used?

**Review by baszalmstra — CHANGES_REQUESTED** [review]
This looks very good! Thanks! 👍 

Most of my comments are about adding some comments, I find it hard to figure out exactly what is going on.

File: crates/mun_codegen/src/ir/types.rs (hunk 1 above)
Comment (Wodann) [reply crates/mun_codegen/src/ir/types.rs:2]: It is required for the `AsValue` macro. I tried including it in the macro itself, but that didn't work. If you have any alternative ideas, please let me know.

File: crates/mun_codegen_macros/src/lib.rs (hunk 2 above)
Comment (Wodann) [reply crates/mun_codegen_macros/src/lib.rs:168]: I can remove them. The code existed before my changes, so I thought they were there for a purpose.

File: crates/mun_codegen_macros/src/lib.rs (hunk 5 above)
Comment (Wodann) [reply crates/mun_codegen_macros/src/lib.rs:98]: You wrote it 😋 (I just left it). I think that you mean that from there on you are generating the actual "final" code.

File: crates/mun_codegen/src/ir/types.rs (hunk 1 above)
Comment (baszalmstra) [reply crates/mun_codegen/src/ir/types.rs:2]: I believe you can also put the use in the generated itself, in the function.

File: crates/mun_codegen_macros/src/lib.rs (hunk 2 above)
Comment (baszalmstra) [reply crates/mun_codegen_macros/src/lib.rs]: Ah yes I remember that I put it there to be able to debug the code.

File: crates/mun_codegen/src/ir/types.rs (hunk 1 above)
Comment (Wodann) [reply crates/mun_codegen/src/ir/types.rs:2]: I'll try it again, but last time I did that it didn't work 😞

**Review by baszalmstra — APPROVED** [review]
